### PR TITLE
Xcode 13 RC compile fix

### PR DESCRIPTION
**Pull request by nighthawk**
The line `free(buffer)` doesn't compile in Xcode 13 RC in my local testing, as buffer is an optional. I've added a guard statement for this, and also one for `input`, just in case.

### CODE REVIEW

**Comment by gongzhang** [comment]
😎 For the impatient.

```
.package(url: "https://github.com/maparoni/Zip.git", .revisionItem("059e7346082d02de16220cd79df7db18ddeba8c3")),
```

Note that this error will only occur on mac or macCatalyst targets.

**Review by danyf90 — APPROVED** [review]

**Review by 08kovalchuk03 — APPROVED** [review]

**Comment by mgadda** [comment]
Came here to submit the same patch. thanks @nighthawk.

**Comment by C4Framework** [comment]
Also came here to submit a patch

**Comment by hamza72x** [comment]
> 😎 For the impatient.
> 
> ```
> .package(url: "https://github.com/maparoni/Zip.git", .revisionItem("059e7346082d02de16220cd79df7db18ddeba8c3")),
> ```
> 
> Note that this error will only occur on mac or macCatalyst targets.

how to do that in `Podfile`? Looks like `Podfile` doesn't support `:revision` type something.

**Comment by gongzhang** [comment]
@hamza72x 

You can try this ⬇️

image

https://guides.cocoapods.org/using/the-podfile.html

**Comment by hamza72x** [comment]
> @hamza72x
> 
> You can try this ⬇️
> 
> image
> 
> https://guides.cocoapods.org/using/the-podfile.html
> 
> **Use _maparoni_'s fork repo. Not the original repo.** 😄

`marmelroy` and `maparoni` looked similar, my bad. I forked `maparoni`'s repo. Thank you.

**Comment by marmelroy** [comment]
Thanks @nighthawk @hamza72x @CognitiveDisson and @C4Framework and sorry for the delay with getting this fix in. I am looking for additional collaborators to help maintain Zip to prevent such long delays. Please let me know if any of you are interested.

**Pull request merged**
