### PR TITLE
Feature/swift3.0

### PR DESCRIPTION
**Pull request by mostafaberg**
* Swift 3.0 support
* Xcode 8 support by @macness-pavelh

### CODE REVIEW

**Comment by marmelroy** [comment]
So... it appears like xctool is broken with Xcode 8 -  see https://github.com/facebook/xctool/issues/704

To fix the tests could you also please change all xctool references in build.sh to xcodebuild?

**Comment by mostafaberg** [comment]
@marmelroy yeah just had a similar issue at work too, will look into it now

**Comment by mostafaberg** [comment]
Done, but it seems like it's no longer triggering the build and shows this message:
[`Branch "swift3.0" not included per configuration.`](https://travis-ci.org/marmelroy/Zip/requests)

**Comment by marmelroy** [comment]
Damn. I forgot that the travis file also states that tests should only run for PRs on master. 

```
# whitelist
branches:
  only:
    - master
```

Adding swift3.0 to that list should fix it. Sorry about all of this. I really appreciate your effort...

**Comment by mostafaberg** [comment]
haha no worries, will add that now 👍

**Comment by mostafaberg** [comment]
Done, I also removed a couple lines regarding `xctool` there since it's not used anymore

**Comment by mostafaberg** [comment]
I see a few warnings during build and one fail, I'll get that sorted out after lunch

**Comment by marmelroy** [comment]
Great. 

So... Good news! The tests are passing for the framework (but failing for the example - I'll fix that on my side). Merging.

**Comment by mostafaberg** [comment]
oh ok, great news 👍  thanks for the help

**Pull request merged**
