### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by ffried**
Since #118 seems to be dead, I've created a new PR.

This adds full SPM support. The following changes were necessary:
- Add Package.swift file
- Move minizip model map and headers into "include" subdirectory (required by SPM)
- Work around some issues with not yet implemented APIs in corelibs-foundation (namely file creation and modification attributes and `FileManager.urls(for:in:)`)
- Refactor test setup to work with SPM
- Generate LinuxMain files for SPM tests
- Let travis run tests with SPM
- Update README

### CODE REVIEW

**Comment by ffried** [comment]
Any news on this?

**Comment by ffried** [comment]
(cc @marmelroy)

**Comment by bryan1anderson** [comment]
please merge this

**Comment by choongng** [comment]
It seems @marmelroy is occupied with other things, I've merged this into my public fork and will continue maintenance there until they are back. https://github.com/choongng/Zip

**Comment by fl034** [comment]
@AvdLee could you merge this?

**Comment by ffried** [comment]
@AvdLee Thanks for the review and for getting this on! 
The CI seems to have stalled. I've added Swift 5.1 support for SPM as well (literally just a copy of the Package.swift declaring 5.1 tools). Let's see if the new CI build now works 🙂

**Comment by AvdLee** [comment]
Looks good! Merging in 🚀

**Comment by svoip** [comment]
@AvdLee Can you make a new release as well? 
It seems package is being recognized, but not it is not yet aligned with the correct version of the library.
I am getting this error:

image

**Comment by mcritz** [comment]
> @AvdLee Can you make a new release as well?
> It seems package is being recognized, but not it is not yet aligned with the correct version of the library.
> I am getting this error:
> 
> image

Confirmed. Using `swift package` also has the same issue.

**Comment by mcritz** [comment]
@svoip Be sure you’re using the latest SPM tools. The top line of your Package.swift file should be:

`// swift-tools-version:5.1`

**Comment by ffried** [comment]
For now, you can also use `master` as target. 
In `Package.swift`, you can use `.branch("master")` instead of `from: "1.1.0"` as target of your dependency.
In Xcode, you can select the target when adding the dependency as well.

**Comment by ffried** [comment]
Or use `.revision("80b1c3005ee25b4c7ce46c4029ac3347e8d5e37e")` if you want to stick to the current HEAD commit of the master branch. Be aware, though, that this might break once `master` progresses.

**Comment by AvdLee** [comment]
@ffried @mcritz I'm not actively working on this project and don't have the time to do a new release. Maybe @marmelroy can make a new release or make one of you capable to do that

**Comment by trevor-sonic** [comment]
I have same issue as @svoip .
I could use `master` but it is not ideal.
I'm using Xcode 11.3

**Comment by marmelroy** [comment]
This should be fixed now

**Pull request merged**
