### PR TITLE
Fix unzipping files within sub directory

### PR DESCRIPTION
**Pull request by gwjakewelton**
## Problem
Unzipping a file with sub directories would fail as the fullPath string was a file path.

## Solution
The last path component has been removed, so all intermediate directories can be created.

A sub directory with .gif has been added to the already existing bb8.zip along with a unit test.

### CODE REVIEW

**Comment by marmelroy** [comment]
Great improvement @gwjakewelton. Thanks a lot!

**Comment by marmelroy** [comment]
@gwjakewelton it seems that for some reason the test you added fails

**Comment by gwjakewelton** [comment]
@marmelroy Test fixed. Looks like I generated the test zip archive wrong. CI is now passing.

**Comment by marmelroy** [comment]
Awesome, thanks

**Pull request merged**
