### PR TITLE
Feature/swift2.3

### PR DESCRIPTION
**Pull request by mostafaberg**
+This PR includes changes to the source files and the test cases that Utilizes Swift 2.3
+Tests have been run and all pass
+Verified filesystem to confirm zip files work on the device properly
+Tested on XCode 8.0b3 (8S174q)

### CODE REVIEW

**Comment by marmelroy** [comment]
Thanks a lot for this @mostafaberg. I just created a Swift 2.3 branch, can you point your PR there and I will accept it. Thanks.

**Comment by nick3389** [comment]
pod 'Zip', :git => 'https://github.com/marmelroy/Zip.git', :branch => 'swift2.3'

is this ok?

**Comment by nick3389** [comment]
Also, i get no such module minizip when building

**Comment by geoffreywiseman** [comment]
The Swift 2.3 branch is gone?

**Comment by marmelroy** [comment]
Hi @geoffreywiseman and @basememara - yup, it was deleted. 

Swift 3.0 was officially released last week and it is now the only officially supported version of Swift for Zip. 

I have, however, brought back the Swift 2.3 branch to ease the transition (it won't be there forever though).

**Comment by basememara** [comment]
Thank you! This will give us all time for us to migrate to Swift 3 in the meantime (and all our dependencies).

**Comment by geoffreywiseman** [comment]
Sure -- I don't expect long-term maintenance of the 2.3 branch, I just want a little time to make the transition. Thanks!

**Pull request merged**
